name: Update Spotify Listening History


on:
schedule:
- cron: '0 * * * *' # every hour on the hour (UTC)
workflow_dispatch: {}


permissions:
contents: write


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: 20
- name: Update history
env:
SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
run: |
node scripts/update-listening-history.mjs
- name: Commit & push (if changed)
run: |
if [[ -n $(git status --porcelain) ]]; then
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add data/*.json
git commit -m "chore: update listening history [skip ci]"
git push
else
echo "No changes to commit."
fi