name: Update Spotify History (daily)

on:
    schedule:
        # 08:00 UTC ≈ midnight PT during standard time; adjust if you prefer.
        - cron: '0 * * * *'
    workflow_dispatch: {}

permissions:
    contents: write

jobs:
    update-history:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install deps (none needed)
              run: echo "No dependencies"

            - name: Fetch Spotify recently played & update JSON
              env:
                  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
                  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
                  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
              run: node scripts/update-listening-history.mjs

            - name: Commit & push changes (if any)
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add data/listening-history.json data/latest.json
                  git diff --cached --quiet && echo "No changes" || git commit -m "chore: update Spotify history $(date -u +'%Y-%m-%d')"
                  git push
