name: Update Spotify

on:
  schedule:
    - cron: '0 * * * *' # hourly, UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone private data repo
        env:
          GH_TOKEN: ${{ secrets.DATA_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/s4chin/consumption-data.git private-data

      - name: Update JSON in private repo
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          DATA_PATH: ${{ github.workspace }}/private-data/listening-history.json
          LATEST_PATH: ${{ github.workspace }}/private-data/latest.json
        run: node scripts/update-listening-history.mjs

      - name: Build static page (no public JSON)
        env:
          DATA_PATH: ${{ github.workspace }}/private-data/listening-history.json
          OUTPUT: spotify-history.html
        run: node scripts/build-page.mjs

      - name: Commit & push public site changes
        run: |
          git add spotify-history.html
          if git diff --cached --quiet --exit-code; then
            echo "No changes to public site. Skipping commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "site: rebuild from private JSON [skip ci]"
            git push
          fi

      - name: Commit & push updated JSON to private repo
        working-directory: private-data
        env:
          GH_TOKEN: ${{ secrets.DATA_REPO_TOKEN }}
        run: |
          git add listening-history.json latest.json || true
          if git diff --cached --quiet --exit-code; then
            echo "No JSON changes. Skipping commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "data: update listening history"
            git push https://x-access-token:${GH_TOKEN}@github.com/s4chin/consumption-data.git HEAD:main
          fi